//
// Created by OchiAnthropos on 24.12.2023.
//

#ifndef AMERICANDEMOCRACYSIMULATOR_RECTANGLECOLLIDER_H
#define AMERICANDEMOCRACYSIMULATOR_RECTANGLECOLLIDER_H
#pragma once
namespace Game {
    class RectangleCollider{
    };
}

#endif //AMERICANDEMOCRACYSIMULATOR_RECTANGLECOLLIDER_H
