//
// Created by OchiAnthropos on 22.12.2023.
//

#ifndef AMERICANDEMOCRACYSIMULATOR_OBJECTS_H
#define AMERICANDEMOCRACYSIMULATOR_OBJECTS_H
#pragma once



#endif //AMERICANDEMOCRACYSIMULATOR_OBJECTS_H
