//
// Created by OchiAnthropos on 22.12.2023.
//

#ifndef AMERICANDEMOCRACYSIMULATOR_GAMEOBJECTS_H
#define AMERICANDEMOCRACYSIMULATOR_GAMEOBJECTS_H
#include "Objects/Objects.h."
#endif //AMERICANDEMOCRACYSIMULATOR_GAMEOBJECTS_H
